title: Jekyll Test
author: Joel Lindberg
navbar-links:
  About: "about"

domain: joellindberg.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://joellindberg.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /jekyll-test                # place folder name if the site is served in a subfolder



# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/